sudo: required
services:
  - docker

before_install:
  - docker build -t goil/react-test -f ./client/Dockerfile.dev ./client

script:
  - ducker run goil/react-test npm test -- --coverage

after_success:
  - docker build -t goil/multi-client ./client
  - docker build -t goil/multi-nginx ./nginx
  - docker build -t goil/multi-server ./server
  - docker build -t goil/multi-worker ./worker

  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - - docker push goil/multi-client
  - - docker push goil/multi-nginx
  - - docker push goil/multi-server
  - - docker push goil/multi-worker